# Generated by Django 5.0 on 2023-12-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={
                "verbose_name": "Competição",
                "verbose_name_plural": "Competições",
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
