# Generated by Django 5.0 on 2023-12-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="competitions/"),
        ),
    ]
