# Generated by Django 5.0 on 2023-12-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_alter_competition_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="max_slots",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total de vagas disponíveis. Se não quiser impor um limite de vagas, defina esse campo como 0",
            ),
        ),
    ]
