# Generated by Django 5.0 on 2023-12-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0003_competition_max_slots"),
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="modality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.modality",
            ),
            preserve_default=False,
        ),
    ]
