# Generated by Django 5.0 on 2023-12-13 05:32

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0003_alter_competition_organizer_delete_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="address",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="city",
            field=models.CharField(default="", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="state",
            field=localflavor.br.models.BRStateField(default="", max_length=2),
            preserve_default=False,
        ),
    ]
