# Generated by Django 5.0 on 2023-12-17 02:35

import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0004_competition_modality"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="subscription_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="Preço da inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="city",
            field=models.CharField(max_length=80, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="datetime",
            field=models.DateTimeField(verbose_name="Data e Horário"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="competitions/", verbose_name="Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="max_slots",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Se não quiser impor um limite de vagas, defina esse campo como 0",
                verbose_name="Número de vagas",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="modality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sports.modality",
                verbose_name="Modalidade",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organizador",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="state",
            field=localflavor.br.models.BRStateField(
                max_length=2, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Título"),
        ),
    ]
