# Generated by Django 5.0 on 2023-12-18 21:09

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0005_competition_subscription_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="city",
            field=models.CharField(blank=True, max_length=80, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="state",
            field=localflavor.br.models.BRStateField(
                blank=True, max_length=2, verbose_name="Estado"
            ),
        ),
    ]
