# Generated by Django 5.0 on 2023-12-19 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0006_alter_competition_address_alter_competition_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="subscription_until",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Prazo de Inscrição"
            ),
            preserve_default=False,
        ),
    ]
