# Generated by Django 5.0 on 2023-12-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0007_competition_subscription_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="subscription_until",
            field=models.DateTimeField(verbose_name="Prazo de inscrição"),
        ),
    ]
