# Generated by Django 5.0.1 on 2024-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0008_alter_competition_subscription_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="avaliacao",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=1,
                verbose_name="Avaliação",
            ),
        ),
    ]
