# Generated by Django 5.0 on 2024-01-30 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0008_alter_competition_subscription_until"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="datetime_end",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Data e Horário de término",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CompetitionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("observations", models.TextField()),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competition",
            name="avaliacoes",
            field=models.ManyToManyField(
                related_name="+",
                through="competitions.CompetitionRate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
