# Generated by Django 5.0 on 2024-01-31 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0009_competition_datetime_end_competitionrate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="competition",
            old_name="avaliacoes",
            new_name="raters",
        ),
        migrations.AlterField(
            model_name="competitionrate",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="competitions.competition",
            ),
        ),
        migrations.AlterField(
            model_name="competitionrate",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (5, "Excelente"),
                    (4, "Ótimo"),
                    (3, "Bom"),
                    (2, "Regular"),
                    (1, "Ruim"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="competitionrate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
