# Generated by Django 5.0.1 on 2024-02-05 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0009_competition_avaliacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="avaliacao",
        ),
        migrations.CreateModel(
            name="CompetitionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "Excelente"),
                            (4, "Ótimo"),
                            (3, "Bom"),
                            (2, "Regular"),
                            (1, "Ruim"),
                        ]
                    ),
                ),
                ("observations", models.TextField()),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Competição",
                "verbose_name_plural": "Avaliações de Competições",
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="raters",
            field=models.ManyToManyField(
                related_name="+",
                through="competitions.CompetitionRate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
