# Generated by Django 5.0 on 2024-02-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0010_remove_competitionsubscription_paid_and_more"),
        ("teams", "0003_alter_team_leader_alter_team_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="subscribed_teams",
            field=models.ManyToManyField(
                related_name="competitions",
                through="competitions.CompetitionSubscription",
                to="teams.team",
            ),
        ),
    ]
