# Generated by Django 5.0.1 on 2024-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0010_remove_competition_avaliacao_competitionrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="datetime_end",
            field=models.DateTimeField(
                default=1, verbose_name="Data e Horário de término"
            ),
            preserve_default=False,
        ),
    ]
