# Generated by Django 5.0 on 2024-02-02 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0010_rename_avaliacoes_competition_raters_and_more"),
        ("competitions", "0011_competition_subscribed_teams"),
    ]

    operations = []
