# Generated by Django 5.0.1 on 2024-02-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0011_competition_datetime_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="datetime_end",
        ),
    ]
