# Generated by Django 5.0 on 2024-02-02 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0011_alter_competitionrate_options"),
        ("competitions", "0012_merge_20240201_2204"),
    ]

    operations = []
