# Generated by Django 5.0.1 on 2024-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0012_remove_competition_datetime_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="datetime_end",
            field=models.DateTimeField(
                default=None, verbose_name="Data e Horário de término"
            ),
        ),
    ]
