# Generated by Django 5.0.1 on 2024-02-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0013_competition_datetime_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="datetime_end",
            field=models.DateTimeField(verbose_name="Data e Horário de término"),
        ),
    ]
