# Generated by Django 5.0 on 2024-02-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0015_alter_competitionresults_competition"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="")),
                ("creation", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documentos de Competição",
            },
        ),
    ]
