# Generated by Django 5.0 on 2024-02-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0016_competitiondocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitiondocument",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="competitions.competition",
                verbose_name="Competição",
            ),
        ),
        migrations.AlterField(
            model_name="competitiondocument",
            name="file",
            field=models.FileField(upload_to="", verbose_name="Arquivo"),
        ),
        migrations.AlterField(
            model_name="competitiondocument",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome do arquivo"),
        ),
        migrations.AlterField(
            model_name="competitionsubscription",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="competitions.competition",
                verbose_name="Competição",
            ),
        ),
        migrations.AddConstraint(
            model_name="competitiondocument",
            constraint=models.UniqueConstraint(
                fields=("competition", "name"),
                name="unique_document_name_per_competition",
            ),
        ),
    ]
