# Generated by Django 5.0 on 2024-02-05 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0017_alter_competitiondocument_competition_and_more"),
        ("teams", "0003_alter_team_leader_alter_team_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionsubscription",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="teams.team",
                verbose_name="Time",
            ),
        ),
    ]
