# Generated by Django 5.0 on 2024-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0019_organizerrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitiondocument",
            options={
                "verbose_name": "Documento de Competição",
                "verbose_name_plural": "Documentos de Competições",
            },
        ),
        migrations.AlterField(
            model_name="organizerrequest",
            name="reject_reason",
            field=models.TextField(blank=True),
        ),
    ]
