# Generated by Django 5.0 on 2024-02-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0020_alter_competitiondocument_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizerrequest",
            name="reject_reason",
        ),
        migrations.AlterField(
            model_name="organizerrequest",
            name="request_reason",
            field=models.TextField(verbose_name="Motivo da Solicitação"),
        ),
    ]
