# Generated by Django 5.0 on 2023-12-13 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="leader",
        ),
        migrations.AddField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="teams.player",
            ),
            preserve_default=False,
        ),
    ]
