# Generated by Django 5.0 on 2023-12-13 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_remove_teammember_leader_team_leader"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "Jogador", "verbose_name_plural": "Jogadores"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Equipe", "verbose_name_plural": "Equipes"},
        ),
    ]
