# Generated by Django 5.0 on 2023-12-17 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
        ("teams", "0002_remove_teammember_player_alter_team_leader_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Líder",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                through="teams.TeamMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membros",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="modality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sports.modality",
                verbose_name="Modalidade",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
    ]
