# Generated by Django 5.0 on 2023-12-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
        ("teams", "0003_alter_player_options_alter_team_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_team_name"
            ),
        ),
    ]
