# Generated by Django 5.0 on 2023-12-14 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_team_unique_team_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="cpf",
        ),
    ]
