# Generated by Django 5.0 on 2023-12-14 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_remove_player_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="user",
            new_name="player",
        ),
    ]
