# Generated by Django 5.0 on 2023-12-13 01:43

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=localflavor.br.models.BRCPFField(max_length=14, null=True),
        ),
    ]
