# Generated by Django 5.0 on 2023-12-14 04:20

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=localflavor.br.models.BRCPFField(
                max_length=14, null=True, unique=True
            ),
        ),
    ]
