# Generated by Django 5.0.1 on 2024-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_cpf_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOrganizer',
            field=models.BooleanField(default=False),
        ),
    ]
