# Generated by Django 5.0.1 on 2024-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizerrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('declined', 'Recusado')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Account Created At'),
        ),
    ]
