# Generated by Django 5.0 on 2023-12-18 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modality",
            options={
                "verbose_name": "Modalidade",
                "verbose_name_plural": "Modalidades",
            },
        ),
        migrations.AlterModelOptions(
            name="sport",
            options={"verbose_name": "Esporte", "verbose_name_plural": "Esportes"},
        ),
    ]
